mkdir wk
cd wk

set RELEASE_TYPE="Release"
:: tell cmake where Python is
set PYTHON_LIBRARY=%PREFIX%\libs\python%PY_VER:~0,1%%PY_VER:~2,1%.lib

cmake .. -G "Ninja" ^
    -Wno-dev ^
    -DCMAKE_BUILD_TYPE:STRING=%RELEASE_TYPE% ^
	-DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
	-DINSTALL_BIN_DIR=%LIBRARY_BIN% ^
	-DINSTALL_INC_DIR=%LIBRARY_INC% ^
	-DINSTALL_LIB_DIR=%LIBRARY_LIB% ^
    -DITK_WRAP_PYTHON:BOOL=ON ^
    -DWRAP_ITK_SWIG_ARGS_PYTHON:STRING='-threads' ^
    -DITK_LEGACY_SILENT:BOOL=ON ^
    -DPYTHON_LIBRARY:PATH=%STDLIB_DIR% ^
    -DPYTHON_EXECUTABLE:PATH=%PYTHON% ^
    -DPY_SITE_PACKAGES_PATH:PATH=%SP_DIR ^
    -DITK_LEGACY_REMOVE:BOOL=OFF ^
    -DITK_USE_FLAT_DIRECTORY_INSTALL:BOOL=ON ^
    -DBUILD_SHARED_LIBS:BOOL=ON ^
    -DBUILD_EXAMPLES:BOOL=OFF ^
    -DBUILD_TESTING:BOOL=OFF ^
    -DITK_BUILD_DEFAULT_MODULES:BOOL=ON ^
    -DITK_INSTALL_NO_DEVELOPMENT:BOOL=ON ^
    -DModule_ITKReview:BOOL=ON ^
    -DITK_USE_REVIEW_STATISTICS:BOOL=ON ^
    -DITK_USE_OPTIMIZED_REGISTRATION_METHODS:BOOL=ON ^
    -DITKV3_COMPATIBILITY:BOOL=ON ^
if errorlevel 1 exit 1

ninja install
if errorlevel 1 exit 1