#!/bin/bash

mkdir build
cd build

BUILD_CONFIG="Release"

cmake .. -G "Ninja" \
    -Wno-dev \
    -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
    -DCMAKE_INSTALL_PREFIX:PATH=${PREFIX} \
    -DCMAKE_INSTALL_RPATH:PATH="${PREFIX}/lib" \
    -DITK_WRAP_PYTHON:BOOL=ON \
    -DWRAP_ITK_SWIG_ARGS_PYTHON:STRING='-threads' \
    -DITK_LEGACY_SILENT:BOOL=ON \
    -DPYTHON_LIBRARY:PATH=${STDLIB_DIR} \
    -DPYTHON_EXECUTABLE:PATH=${PYTHON} \
    -DPY_SITE_PACKAGES_PATH:PATH=${SP_DIR} \
    -DITK_LEGACY_REMOVE:BOOL=OFF \
    -DITK_USE_FLAT_DIRECTORY_INSTALL:BOOL=ON \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DBUILD_EXAMPLES:BOOL=OFF \
    -DBUILD_TESTING:BOOL=OFF \
    -DITK_BUILD_DEFAULT_MODULES:BOOL=ON \
    -DITK_INSTALL_NO_DEVELOPMENT:BOOL=ON \
    -DModule_ITKReview:BOOL=ON \
    -DITK_USE_REVIEW_STATISTICS:BOOL=ON \
    -DITK_USE_OPTIMIZED_REGISTRATION_METHODS:BOOL=ON \
    -DITKV3_COMPATIBILITY:BOOL=ON \
    -DITK_USE_SYSTEM_GDCM:BOOL=ON \
    -DITK_USE_SYSTEM_EXPAT:BOOL=ON \
    -DITK_USE_SYSTEM_HDF5:BOOL=ON \
    -DITK_USE_SYSTEM_JPEG:BOOL=ON \
    -DITK_USE_SYSTEM_OPENJPEG:BOOL=ON \
    -DITK_USE_SYSTEM_PNG:BOOL=ON \
    -DITK_USE_SYSTEM_TIFF:BOOL=ON \
    -DITK_USE_SYSTEM_ZLIB:BOOL=ON

ninja install