zipped_keys:
  - [python, python_impl, numpy, is_python_min]

python:
  - 3.11.* *_cpython
  - 3.12.* *_cpython

python_impl:
  - cpython
  - cpython

numpy:
  - "2.1.*"
  - "2.1.*"

is_python_min:
  - false
  - false