"""Add Python distribution metadata to the combined conda ITK package.

The CMake source build installs the shared ``itk`` package without the metadata
that lets Python tooling recognize the umbrella and component distributions.
"""

from __future__ import annotations

import os
import re
from pathlib import Path


version = os.environ["PKG_VERSION"]
site_packages = Path(os.environ["SP_DIR"])

# Keep this dependency graph aligned with ITKPythonPackage.
component_dependencies = {
    "itk-core": ["numpy"],
    "itk-numerics": [f"itk-core=={version}"],
    "itk-io": [f"itk-core=={version}"],
    "itk-filtering": [f"itk-numerics=={version}"],
    "itk-registration": [f"itk-filtering=={version}"],
    "itk-segmentation": [f"itk-filtering=={version}"],
}
distributions = {
    "itk": [
        *(f"{name}=={version}" for name in component_dependencies),
        "numpy",
    ],
    **component_dependencies,
}

for distribution_name, dependencies in distributions.items():
    normalized_name = re.sub(r"[-_.]+", "_", distribution_name)
    dist_info_dir = site_packages / f"{normalized_name}-{version}.dist-info"
    dist_info_dir.mkdir(parents=True, exist_ok=False)

    metadata_lines = [
        "Metadata-Version: 2.1",
        f"Name: {distribution_name}",
        f"Version: {version}",
        "Summary: ITK Python package metadata generated by conda-forge",
        "Requires-Python: >=3.8",
        *(f"Requires-Dist: {dependency}" for dependency in dependencies),
        "",
    ]
    (dist_info_dir / "METADATA").write_text("\n".join(metadata_lines), encoding="utf-8")
    (dist_info_dir / "INSTALLER").write_text("conda\n", encoding="utf-8")
    (dist_info_dir / "top_level.txt").write_text("itk\n", encoding="utf-8")
