{% set version = "4.13.0" %}
{% set build_number = 1 %}
{% set minor_version = ".".join(version.split(".")[:2]) %}
{% set source_sha256 = "37122d65b89699df33f34e0859f1e7adf5a6222060dc1c47383ff7aa4531223a" %} 

package:
  name: itk
  version: {{ version }}

source:
  url: https://github.com/Kitware/ITK/archive/v{{ version }}.tar.gz
  sha256: {{ source_sha256 }}


build:
  number: {{ build_number }}
  skip: True  # [win32]
  features:
    - vc9   # [win and py27]
    - vc14  # [win and py35]
    - vc14  # [win and py36]

requirements:
  build:
    - toolchain
    - cmake
    - ninja
    - python
  run:
    - python
    - future  # used in the generated python wrappers
    - numpy

test:
  imports:
    - itk

about:
  home: http://www.itk.org/
  license: Apache 2.0
  summary: ITK is an open-source toolkit for multidimensional image analysis
  doc_url: https://itk.org/ITK/help/documentation.html
  dev_url: https://github.com/InsightSoftwareConsortium/ITK

extra:
  recipe-maintainers:
    - thewtex
    - ericdill
    - rlizzo
