{% set name = "itk" %}
{% set version = "5.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/InsightSoftwareConsortium/ITKPythonPackage/archive/v{{version}}.tar.gz
  sha256: cca1bd3ab5ac0f639f22760ab25b08c917107c44a770ab79a67da1d51c325be3

build:
  number: 1
  skip: True  # [win32 or (win64 and py2k)]

requirements:
  build:
    - cmake   >=3.10
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python
    - numpy

test:
  imports:
    - itk

about:
  home: https://www.itk.org/
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - NOTICE
  summary: ITK is an open-source toolkit for multidimensional image analysis
  doc_url: https://itk.org/ITK/help/documentation.html
  dev_url: https://github.com/InsightSoftwareConsortium/ITK

extra:
  recipe-maintainers:
    - thewtex
