{% set name = "itk" %}
{% set version = "5.4.0" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/InsightSoftwareConsortium/ITK/releases/download/v{{ version }}/InsightToolkit-{{ version }}.tar.gz
  md5: 5f7b1d3e150ebbce9ab8fb6c6f27cbe4

build:
  number: 0
  skip: True  # [win32 or (win64 and py2k)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - wheel
    - numpy
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - itk
  requires:
    - pip

about:
  home: https://www.itk.org/
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - NOTICE
  summary: ITK is an open-source toolkit for multidimensional image analysis
  doc_url: https://itk.org/ITK/help/documentation.html
  dev_url: https://github.com/InsightSoftwareConsortium/ITK

extra:
  recipe-maintainers:
    - hanayik
    - thewtex
