build_platform:
  linux_aarch64: linux_64
github_actions:
  free_disk_space: true
provider:
  osx_arm64: azure
  win: github_actions
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
