travis:
  secure:
    BINSTAR_TOKEN: IWZZ4+qdq3zmsc1sFwUhVonn0kj5Sk9G8xKKPr/E5ZtsOG7abtcmiDQyNVbpgeb+Q7HoSzmOf0iEjACoqIQV7+15/nfyTfxsywZdPRE+LV/PtHLTXOSeLdTGzVRihkgsza4Od/pO6U6hhy7E99kv+ieVHOjzow9G5UuEj+hJicSu8ce3FmdHushy0M+dKlBpv4f0Dy+UGVGVuWIL3eNuUqjk4ui+OCBOZwzpdK6Qky1wZg8JjY5EZsMXzzAnMaRDXPVm/WnzuTXO7f0KASpA0QNhCg7LVEmPbbpg3iEyxbBen4n9S7O/6YPaZQgXYcVkh4lYE/CpXjlerepl0GqssP6nOGGSzIojMlyNRqo3k6QHoK1lSvm2SAjQb6dlwDTNWvzRPzVJk9yGc5BMpd1cJWfx8nX9ZF5ay++xLtFsmzcS+iRebDxeMK/qRlnByG7QmVzRnbLTtZbkxISVQZl8P+Y8fR007xjMmozAqbGDr/n+eyr8we/L5D/qVrulpTCBgfASKefiHRUC4enflC9xnXJ7ltBQSswXW91xId1IH87o+S79kfPfdd2Z5DQHSlTRwvOMqyEjphHndYtd/LJWyVhCTkbpDWMFfCWtQZTdhLE0Zz3M7GXitMziiAR8ofXGqeltIAcmHz+5VRmlOOiekxAIe0uRUtnOPgmfcyo1YwI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
