travis:
  secure:
    BINSTAR_TOKEN: ijg4RkFz8uteopItdtUFVK9lFZ9lLFzDt7iR+eEu0MdAPJGnBLuKficKj98R0FT44JwG+fUMTUlOwjalvvJ6c8mmCXM2fwwggwtrkaGHe9K3qBq3pXVso6PO/qI7ZlnmzVJpmRxZUywjbepIOj+g8/3Y8A6mCclWRU5V6JpXxGVWkZDoLA4/FXcYLzWT451ZAVyN2jDoCmZxejABdkgFlL9qgBEzTlUc+BKHBuOaqolXpJeDa/Z4AhaUFbQ/ObsqaevPFFHxp7mWpPla33cHuYuRuh1dg0pUuU2X6J589uCEe8zuR8LAsyZN4ETtDmgPCVI5NOJECRkgWjASXVQAY04u9Fl8WjrpqeKss8aE4KsjK7LtDEM48DkM4JNso4V1a2+NhsActAxPdrTC3sGuxpvYiidQ+T3mGk1qKd1rEAe0VY3URlVz50xxwhYWL9Tafk9AZZbeFY5kugr+eSDVO0rOhHZaPyK3jG3ssmm2DQfz4ODAc7yf3c5UG7659SSyutZefgEaOFdtRGEzflTJBDJEN2wsn7RXHSGlyOLIzqVJEN55DZOIpf2HWp63ft30f1lkXK6/DyTwKMNvxp0b6WLFfgo3tdwewmkGDpKsAKFZbXVa7IcPxou5ag4wh7TE++QSSy0KUA/nx8ZegaSyyZh+BcGn9yrHZ8+TYXLT5/g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4

provider:
  osx: circle
